version: '3'
services:
  training:
    image: training
    build: .
    ports:
      - "8888:8888"
    # Connecting spacy_model and training.ipynb as volumes to persist modifications and training results outside of the container
    volumes: 
      - ./spacy_model:/training/spacy_model
      - ./training.ipynb:/training/training.ipynb